require('dotenv').config();
const mongoose = require('mongoose');

const User = require('../models/User');
const Category = require('../models/Category');
const Product = require('../models/Product');
const Customer = require('../models/Customer');
const Order = require('../models/Order');
const InventoryTransaction = require('../models/InventoryTransaction');
const Delivery = require('../models/Delivery');
const Payment = require('../models/Payment');
const StoreSettings = require('../models/StoreSettings');
const Notification = require('../models/Notification');

const seedAll = async () => {
  try {
    console.log('[Seed] Clearing existing collections...');
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      Product.deleteMany({}),
      Customer.deleteMany({}),
      Order.deleteMany({}),
      InventoryTransaction.deleteMany({}),
      Delivery.deleteMany({}),
      Payment.deleteMany({}),
      StoreSettings.deleteMany({}),
      Notification.deleteMany({}),
    ]);

    // Store Settings
    await StoreSettings.create({
      storeName: 'LocalKart Kirana & Daily Needs',
      tagline: 'Fresh Groceries & Household Essentials At Your Doorstep',
      phone: '+91 98100 23456',
      email: 'store@localkart.com',
      address: 'Shop No. 7 & 8, Main Market, Block C, Green Park',
      city: 'New Delhi',
      pincode: '110016',
      gstin: '07AAACL9999F1Z2',
      currency: '₹',
      deliveryChargeDefault: 30,
      freeDeliveryThreshold: 499,
      receiptFooter: 'Thank you for shopping at LocalKart! WhatsApp your grocery list to +91 98100 23456 for free delivery on orders above ₹499.',
    });

    // Users
    const adminUser = await User.create({
      name: 'Ramesh Sharma (Owner)',
      email: 'admin@localkart.com',
      password: 'Admin@12345',
      phone: '+91 98100 23456',
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    });

    const staffUsers = await Promise.all([
      User.create({
        name: 'Vikas Gupta (Store Manager)',
        email: 'staff1@localkart.com',
        password: 'Staff@12345',
        phone: '+91 98100 11001',
        role: 'STAFF',
      }),
      User.create({
        name: 'Pooja Verma (Cashier)',
        email: 'staff2@localkart.com',
        password: 'Staff@12345',
        phone: '+91 98100 11002',
        role: 'STAFF',
      }),
      User.create({
        name: 'Amit Patel (Inventory Incharge)',
        email: 'staff3@localkart.com',
        password: 'Staff@12345',
        phone: '+91 98100 11003',
        role: 'STAFF',
      }),
      User.create({
        name: 'Sunita Rao (Order Desk)',
        email: 'staff4@localkart.com',
        password: 'Staff@12345',
        phone: '+91 98100 11004',
        role: 'STAFF',
      }),
      User.create({
        name: 'Deepak Joshi (Billing Associate)',
        email: 'staff5@localkart.com',
        password: 'Staff@12345',
        phone: '+91 98100 11005',
        role: 'STAFF',
      }),
    ]);

    const deliveryPartners = await Promise.all([
      User.create({
        name: 'Suresh Kumar (Rider 1)',
        email: 'delivery1@localkart.com',
        password: 'Delivery@12345',
        phone: '+91 98711 55661',
        role: 'DELIVERY',
      }),
      User.create({
        name: 'Rahul Yadav (Rider 2)',
        email: 'delivery2@localkart.com',
        password: 'Delivery@12345',
        phone: '+91 98711 55662',
        role: 'DELIVERY',
      }),
    ]);

    const sampleCustomerUser = await User.create({
      name: 'Anjali Deshmukh',
      email: 'customer1@localkart.com',
      password: 'Customer@12345',
      phone: '+91 98200 44551',
      role: 'CUSTOMER',
    });

    // Categories
    const categoriesData = [
      { name: 'Flours & Grains', description: 'Atta, Basmati Rice, Dals, Pulses', icon: 'Wheat' },
      { name: 'Dairy & Bakery', description: 'Fresh Milk, Butter, Bread, Paneer', icon: 'Milk' },
      { name: 'Edible Oils & Ghee', description: 'Mustard oil, Sunflower oil, Desi Ghee', icon: 'Droplet' },
      { name: 'Spices & Masalas', description: 'Haldi, Mirch, Garam Masala, Salt, Sugar', icon: 'Sparkles' },
      { name: 'Tea & Coffee', description: 'Chai patti, Green tea, Instant coffee', icon: 'Coffee' },
      { name: 'Snacks & Biscuits', description: 'Namkeen, Chips, Biscuits, Cookies', icon: 'Cookie' },
      { name: 'Beverages & Cold Drinks', description: 'Juices, Sodas, Health drinks', icon: 'GlassWater' },
      { name: 'Personal Care & Hygiene', description: 'Soaps, Shampoos, Toothpaste, Handwash', icon: 'Smile' },
      { name: 'Household & Cleaning', description: 'Detergents, Dishwash, Cleaners', icon: 'Sparkle' },
    ];

    const categories = await Category.insertMany(categoriesData);
    const catMap = {};
    categories.forEach((c) => {
      catMap[c.name] = c._id;
    });

    // 50 Products
    const productsData = [
      {
        name: 'Aashirvaad Shudh Chakki Atta (5 kg)',
        sku: 'GRAIN-ATT-001',
        barcode: '8901030388412',
        category: catMap['Flours & Grains'],
        brand: 'Aashirvaad',
        description: '100% pure whole wheat flour processed with traditional stone chakki.',
        purchasePrice: 220,
        sellingPrice: 265,
        discount: 10,
        gst: 0,
        stockQuantity: 45,
        minimumStockLevel: 10,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Fortune Everyday Basmati Rice (5 kg)',
        sku: 'GRAIN-RIC-002',
        barcode: '8906007281014',
        category: catMap['Flours & Grains'],
        brand: 'Fortune',
        description: 'Aromatic long grain basmati rice ideal for everyday cooking.',
        purchasePrice: 340,
        sellingPrice: 410,
        discount: 20,
        gst: 0,
        stockQuantity: 38,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Tata Sampann Unpolished Toor Dal (1 kg)',
        sku: 'GRAIN-DAL-003',
        barcode: '8904043901115',
        category: catMap['Flours & Grains'],
        brand: 'Tata Sampann',
        description: 'Nutrient-rich unpolished arhar/toor dal without chemical polish.',
        purchasePrice: 145,
        sellingPrice: 175,
        discount: 5,
        gst: 0,
        stockQuantity: 60,
        minimumStockLevel: 12,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Tata Sampann Chana Dal (1 kg)',
        sku: 'GRAIN-DAL-004',
        barcode: '8904043901122',
        category: catMap['Flours & Grains'],
        brand: 'Tata Sampann',
        description: 'Wholesome chana dal sourced directly from farmers.',
        purchasePrice: 95,
        sellingPrice: 118,
        discount: 0,
        gst: 0,
        stockQuantity: 40,
        minimumStockLevel: 10,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Rajdhani Sooji / Semolina (500 g)',
        sku: 'GRAIN-SOO-005',
        barcode: '8901248100101',
        category: catMap['Flours & Grains'],
        brand: 'Rajdhani',
        description: 'Fine granulated roasted semolina for halwa, upma, and idli.',
        purchasePrice: 32,
        sellingPrice: 42,
        discount: 2,
        gst: 0,
        stockQuantity: 30,
        minimumStockLevel: 6,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Rajdhani Besan / Gram Flour (1 kg)',
        sku: 'GRAIN-BES-006',
        barcode: '8901248100200',
        category: catMap['Flours & Grains'],
        brand: 'Rajdhani',
        description: 'Pure 100% chana dal flour for crispy pakoras and snacks.',
        purchasePrice: 85,
        sellingPrice: 105,
        discount: 5,
        gst: 0,
        stockQuantity: 28,
        minimumStockLevel: 5,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Organic Kabuli Chana (1 kg)',
        sku: 'GRAIN-KAB-007',
        barcode: '8906028190012',
        category: catMap['Flours & Grains'],
        brand: 'NatureFresh',
        description: 'Large grain chickpeas for delicious chole bhature.',
        purchasePrice: 130,
        sellingPrice: 160,
        discount: 0,
        gst: 0,
        stockQuantity: 4, // Low stock
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Amul Taaza Toned Fresh Milk (1 L Pouch)',
        sku: 'DAIR-MLK-008',
        barcode: '8901262010014',
        category: catMap['Dairy & Bakery'],
        brand: 'Amul',
        description: 'Homogenized toned pasteurized milk with 3.0% fat.',
        purchasePrice: 52,
        sellingPrice: 56,
        discount: 0,
        gst: 0,
        stockQuantity: 50,
        minimumStockLevel: 15,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Amul Salted Butter (500 g)',
        sku: 'DAIR-BUT-009',
        barcode: '8901262010106',
        category: catMap['Dairy & Bakery'],
        brand: 'Amul',
        description: 'Utterly butterly delicious creamy pasteurized butter.',
        purchasePrice: 240,
        sellingPrice: 275,
        discount: 10,
        gst: 12,
        stockQuantity: 24,
        minimumStockLevel: 6,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Amul Malai Paneer (200 g)',
        sku: 'DAIR-PAN-010',
        barcode: '8901262010205',
        category: catMap['Dairy & Bakery'],
        brand: 'Amul',
        description: 'Rich and soft cottage cheese cubes packed with pure dairy protein.',
        purchasePrice: 78,
        sellingPrice: 92,
        discount: 2,
        gst: 5,
        stockQuantity: 18,
        minimumStockLevel: 5,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Britannia 100% Whole Wheat Brown Bread (400 g)',
        sku: 'BAKE-BRD-011',
        barcode: '8901063010311',
        category: catMap['Dairy & Bakery'],
        brand: 'Britannia',
        description: 'Fiber-rich nutritious brown bread baked fresh every morning.',
        purchasePrice: 40,
        sellingPrice: 50,
        discount: 0,
        gst: 0,
        stockQuantity: 15,
        minimumStockLevel: 5,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Mother Dairy Fresh Curd / Dahi (400 g)',
        sku: 'DAIR-CUR-012',
        barcode: '8901648001018',
        category: catMap['Dairy & Bakery'],
        brand: 'Mother Dairy',
        description: 'Thick, creamy, naturally set curd rich in gut probiotics.',
        purchasePrice: 32,
        sellingPrice: 38,
        discount: 0,
        gst: 0,
        stockQuantity: 2, // Low stock demo
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Fortune Kachi Ghani Mustard Oil (1 L Pouch)',
        sku: 'OIL-MUS-013',
        barcode: '8906007282028',
        category: catMap['Edible Oils & Ghee'],
        brand: 'Fortune',
        description: 'Cold-pressed pungent mustard oil enriched with Omega 3.',
        purchasePrice: 135,
        sellingPrice: 158,
        discount: 5,
        gst: 5,
        stockQuantity: 40,
        minimumStockLevel: 10,
        unit: 'litre',
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Amul Pure Desi Ghee (1 L Carton)',
        sku: 'OIL-GHE-014',
        barcode: '8901262020013',
        category: catMap['Edible Oils & Ghee'],
        brand: 'Amul',
        description: 'Traditional aromatic golden cow ghee crafted from fresh cream.',
        purchasePrice: 560,
        sellingPrice: 650,
        discount: 30,
        gst: 12,
        stockQuantity: 25,
        minimumStockLevel: 5,
        unit: 'litre',
        image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Saffola Gold Pro Healthy Lifestyle Oil (1 L)',
        sku: 'OIL-REF-015',
        barcode: '8901088012014',
        category: catMap['Edible Oils & Ghee'],
        brand: 'Saffola',
        description: 'Dual-seed blend of rice bran and sunflower oil for a healthy heart.',
        purchasePrice: 160,
        sellingPrice: 185,
        discount: 10,
        gst: 5,
        stockQuantity: 22,
        minimumStockLevel: 6,
        unit: 'litre',
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Tata Salt Vacuum Evaporated Iodised (1 kg)',
        sku: 'SPIC-SLT-016',
        barcode: '8904043900019',
        category: catMap['Spices & Masalas'],
        brand: 'Tata',
        description: 'Desh Ka Namak. Pure vacuum evaporated iodised white salt.',
        purchasePrice: 22,
        sellingPrice: 28,
        discount: 0,
        gst: 0,
        stockQuantity: 80,
        minimumStockLevel: 20,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Catch Turmeric / Haldi Powder (200 g)',
        sku: 'SPIC-HLD-017',
        barcode: '8901192101019',
        category: catMap['Spices & Masalas'],
        brand: 'Catch',
        description: 'Rich golden turmeric powder ground with low temperature grinding.',
        purchasePrice: 52,
        sellingPrice: 65,
        discount: 3,
        gst: 5,
        stockQuantity: 42,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'MDH Deggi Mirch Powder (100 g)',
        sku: 'SPIC-MRC-018',
        barcode: '8901768001013',
        category: catMap['Spices & Masalas'],
        brand: 'MDH',
        description: 'Special mild Kashmiri blend that imparts radiant red color.',
        purchasePrice: 68,
        sellingPrice: 84,
        discount: 4,
        gst: 5,
        stockQuantity: 35,
        minimumStockLevel: 6,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Everest Garam Masala (100 g)',
        sku: 'SPIC-GAR-019',
        barcode: '8901786010018',
        category: catMap['Spices & Masalas'],
        brand: 'Everest',
        description: 'Handpicked blend of 13 whole aromatic spices for curries.',
        purchasePrice: 72,
        sellingPrice: 90,
        discount: 5,
        gst: 5,
        stockQuantity: 30,
        minimumStockLevel: 6,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Madhur Pure & Hygienic Sugar (1 kg)',
        sku: 'SPIC-SUG-020',
        barcode: '8906014410018',
        category: catMap['Spices & Masalas'],
        brand: 'Madhur',
        description: 'Sulphur-free sparkling white refined crystal sugar.',
        purchasePrice: 44,
        sellingPrice: 52,
        discount: 0,
        gst: 0,
        stockQuantity: 65,
        minimumStockLevel: 15,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Tata Tea Gold Leaf Tea (500 g)',
        sku: 'BEV-TEA-021',
        barcode: '8901052001016',
        category: catMap['Tea & Coffee'],
        brand: 'Tata Tea',
        description: 'Exquisite blend of strong Assam CTC tea with gentle aroma long leaves.',
        purchasePrice: 280,
        sellingPrice: 340,
        discount: 20,
        gst: 5,
        stockQuantity: 32,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Nescafe Classic Instant Coffee Jar (100 g)',
        sku: 'BEV-COF-022',
        barcode: '8901058852329',
        category: catMap['Tea & Coffee'],
        brand: 'Nescafe',
        description: 'Signature rich roast instant coffee granules for morning punch.',
        purchasePrice: 295,
        sellingPrice: 360,
        discount: 15,
        gst: 18,
        stockQuantity: 20,
        minimumStockLevel: 5,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Wagh Bakri Premium CTC Tea (1 kg)',
        sku: 'BEV-TEA-023',
        barcode: '8901764000102',
        category: catMap['Tea & Coffee'],
        brand: 'Wagh Bakri',
        description: 'Strong authentic Gujarati masala chai base for daily brewing.',
        purchasePrice: 420,
        sellingPrice: 510,
        discount: 25,
        gst: 5,
        stockQuantity: 0, // Out of stock demo!
        minimumStockLevel: 5,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Parle-G Glucose Biscuits (800 g Family Pack)',
        sku: 'SNCK-PAR-024',
        barcode: '8901719101014',
        category: catMap['Snacks & Biscuits'],
        brand: 'Parle',
        description: "India's favorite golden glucose biscuits for chai dipping.",
        purchasePrice: 68,
        sellingPrice: 85,
        discount: 5,
        gst: 18,
        stockQuantity: 50,
        minimumStockLevel: 10,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Britannia Good Day Butter Cookies (600 g)',
        sku: 'SNCK-GDY-025',
        barcode: '8901063011028',
        category: catMap['Snacks & Biscuits'],
        brand: 'Britannia',
        description: 'Rich butter cookies with playful smiles on every biscuit.',
        purchasePrice: 110,
        sellingPrice: 140,
        discount: 10,
        gst: 18,
        stockQuantity: 36,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Haldiram Bhujia Sev (400 g)',
        sku: 'SNCK-BHU-026',
        barcode: '8904004401018',
        category: catMap['Snacks & Biscuits'],
        brand: 'Haldirams',
        description: 'Crispy spicy tepary bean and gram flour namkeen snack.',
        purchasePrice: 90,
        sellingPrice: 115,
        discount: 5,
        gst: 12,
        stockQuantity: 44,
        minimumStockLevel: 10,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Maggi 2-Minute Masala Noodles (Pack of 12)',
        sku: 'SNCK-MAG-027',
        barcode: '8901058850011',
        category: catMap['Snacks & Biscuits'],
        brand: 'Nestle Maggi',
        description: 'Classic favorite instant noodles packed with the famous tastemaker.',
        purchasePrice: 145,
        sellingPrice: 172,
        discount: 10,
        gst: 18,
        stockQuantity: 32,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Lays India\'s Magic Masala Potato Chips (115 g)',
        sku: 'SNCK-LAY-028',
        barcode: '8901491101012',
        category: catMap['Snacks & Biscuits'],
        brand: 'Lays',
        description: 'Crispy ruffled potato chips seasoned with authentic Indian spice mix.',
        purchasePrice: 38,
        sellingPrice: 50,
        discount: 0,
        gst: 12,
        stockQuantity: 40,
        minimumStockLevel: 10,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Oreo Original Vanilla Creme Biscuits (300 g)',
        sku: 'SNCK-ORE-029',
        barcode: '8901233010019',
        category: catMap['Snacks & Biscuits'],
        brand: 'Cadbury Oreo',
        description: 'Rich dark cocoa biscuits sandwiched with sweet vanilla cream.',
        purchasePrice: 70,
        sellingPrice: 90,
        discount: 5,
        gst: 18,
        stockQuantity: 28,
        minimumStockLevel: 6,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Coca Cola Original Soft Drink (750 ml Pet Bottle)',
        sku: 'BEV-COK-030',
        barcode: '8901764020100',
        category: catMap['Beverages & Cold Drinks'],
        brand: 'Coca Cola',
        description: 'Sparkling refreshing cola flavor best served chilled.',
        purchasePrice: 32,
        sellingPrice: 40,
        discount: 0,
        gst: 28,
        stockQuantity: 36,
        minimumStockLevel: 8,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Real Fruit Power Mixed Fruit Juice (1 L Tetra)',
        sku: 'BEV-JUC-031',
        barcode: '8901207010016',
        category: catMap['Beverages & Cold Drinks'],
        brand: 'Dabur Real',
        description: 'Delicious real fruit juice blend of 9 seasonal fruits with Vitamin C.',
        purchasePrice: 105,
        sellingPrice: 130,
        discount: 10,
        gst: 12,
        stockQuantity: 25,
        minimumStockLevel: 5,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Thums Up Charged Carbonated Drink (2 L)',
        sku: 'BEV-THU-032',
        barcode: '8901764020209',
        category: catMap['Beverages & Cold Drinks'],
        brand: 'Thums Up',
        description: 'Taste the thunder with strong fizzy cola kick.',
        purchasePrice: 75,
        sellingPrice: 95,
        discount: 5,
        gst: 28,
        stockQuantity: 22,
        minimumStockLevel: 5,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Red Bull Energy Drink Can (250 ml)',
        sku: 'BEV-RBL-033',
        barcode: '9002490100070',
        category: catMap['Beverages & Cold Drinks'],
        brand: 'Red Bull',
        description: 'Vitalizes body and mind with caffeine and taurine.',
        purchasePrice: 100,
        sellingPrice: 125,
        discount: 0,
        gst: 28,
        stockQuantity: 15,
        minimumStockLevel: 4,
        unit: 'can',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Dettol Original Germ Protection Bathing Soap (Pack of 4x125g)',
        sku: 'PERS-DET-034',
        barcode: '8901396001014',
        category: catMap['Personal Care & Hygiene'],
        brand: 'Dettol',
        description: 'Antibacterial germ defence soap recommended by doctors.',
        purchasePrice: 165,
        sellingPrice: 200,
        discount: 15,
        gst: 18,
        stockQuantity: 30,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Colgate Strong Teeth Dental Cream Toothpaste (500 g Saver)',
        sku: 'PERS-COL-035',
        barcode: '8901314010107',
        category: catMap['Personal Care & Hygiene'],
        brand: 'Colgate',
        description: 'Calcium boost formula that adds natural calcium to teeth enamel.',
        purchasePrice: 210,
        sellingPrice: 260,
        discount: 20,
        gst: 18,
        stockQuantity: 25,
        minimumStockLevel: 6,
        unit: 'piece',
        image: 'https://images.unsplash.com/photo-1559591937-e1032b4b455b?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Head & Shoulders Anti-Dandruff Cool Menthol Shampoo (650 ml)',
        sku: 'PERS-HNS-036',
        barcode: '4902430730101',
        category: catMap['Personal Care & Hygiene'],
        brand: 'Head & Shoulders',
        description: '100% flake-free scalp with icy cool tingling menthol.',
        purchasePrice: 480,
        sellingPrice: 599,
        discount: 50,
        gst: 18,
        stockQuantity: 18,
        minimumStockLevel: 4,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Lifebuoy Total Germ Protection Handwash Refill Pouch (750 ml)',
        sku: 'PERS-LFB-037',
        barcode: '8901030701013',
        category: catMap['Personal Care & Hygiene'],
        brand: 'Lifebuoy',
        description: 'Active silver formula removes 99.9% germs in 10 seconds.',
        purchasePrice: 95,
        sellingPrice: 119,
        discount: 10,
        gst: 18,
        stockQuantity: 3, // Low stock demo
        minimumStockLevel: 6,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Nivea Soft Light Moisturizer Cream Tub (200 ml)',
        sku: 'PERS-NIV-038',
        barcode: '4005808801012',
        category: catMap['Personal Care & Hygiene'],
        brand: 'Nivea',
        description: 'Non-greasy hydrating cream with Jojoba oil and Vitamin E.',
        purchasePrice: 240,
        sellingPrice: 310,
        discount: 20,
        gst: 18,
        stockQuantity: 20,
        minimumStockLevel: 5,
        unit: 'piece',
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Surf Excel Quick Wash Detergent Powder (2 kg)',
        sku: 'HOUS-SRF-039',
        barcode: '8901030010016',
        category: catMap['Household & Cleaning'],
        brand: 'Surf Excel',
        description: 'Removes tough stains like tea, gravy, and mud in 1 stroke.',
        purchasePrice: 285,
        sellingPrice: 350,
        discount: 25,
        gst: 18,
        stockQuantity: 30,
        minimumStockLevel: 8,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Vim Dishwash Liquid Lemon Gel Bottle (750 ml)',
        sku: 'HOUS-VIM-040',
        barcode: '8901030501019',
        category: catMap['Household & Cleaning'],
        brand: 'Vim',
        description: 'Power of 100 lemons degreases non-stick and steel cookware.',
        purchasePrice: 155,
        sellingPrice: 195,
        discount: 15,
        gst: 18,
        stockQuantity: 35,
        minimumStockLevel: 8,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Lizol Citrus Disinfectant Surface Floor Cleaner (1 L)',
        sku: 'HOUS-LIZ-041',
        barcode: '8901396030014',
        category: catMap['Household & Cleaning'],
        brand: 'Lizol',
        description: 'Kills 99.9% germs, leaving a pleasant citrus fragrance.',
        purchasePrice: 175,
        sellingPrice: 220,
        discount: 20,
        gst: 18,
        stockQuantity: 28,
        minimumStockLevel: 6,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Harpic Power Plus Disinfectant Toilet Cleaner (1 L)',
        sku: 'HOUS-HAR-042',
        barcode: '8901396040013',
        category: catMap['Household & Cleaning'],
        brand: 'Harpic',
        description: '10x better stain removal than bleaching powder.',
        purchasePrice: 160,
        sellingPrice: 198,
        discount: 10,
        gst: 18,
        stockQuantity: 32,
        minimumStockLevel: 6,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Good Knight Gold Flash Liquid Mosquito Vaporizer Machine + Refill',
        sku: 'HOUS-GDK-043',
        barcode: '8901023010017',
        category: catMap['Household & Cleaning'],
        brand: 'Good Knight',
        description: "India's most powerful liquid electric mosquito repellent combo.",
        purchasePrice: 110,
        sellingPrice: 135,
        discount: 10,
        gst: 18,
        stockQuantity: 24,
        minimumStockLevel: 5,
        unit: 'piece',
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Scotch-Brite Heavy Duty Scrub Sponge (Pack of 3)',
        sku: 'HOUS-SCB-044',
        barcode: '8901361010014',
        category: catMap['Household & Cleaning'],
        brand: 'Scotch-Brite',
        description: 'Dual action sponge and abrasive scrub pad for spotless utensils.',
        purchasePrice: 70,
        sellingPrice: 90,
        discount: 5,
        gst: 18,
        stockQuantity: 40,
        minimumStockLevel: 10,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Comfort After Wash Morning Fresh Fabric Conditioner (860 ml)',
        sku: 'HOUS-COM-045',
        barcode: '8901030601016',
        category: catMap['Household & Cleaning'],
        brand: 'Comfort',
        description: 'Softens clothes and provides 14-day long-lasting fragrance.',
        purchasePrice: 190,
        sellingPrice: 240,
        discount: 20,
        gst: 18,
        stockQuantity: 18,
        minimumStockLevel: 5,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Premier Special Kitchen Paper Towels (Pack of 2 Rolls)',
        sku: 'HOUS-PAP-046',
        barcode: '8901413010014',
        category: catMap['Household & Cleaning'],
        brand: 'Premier',
        description: 'Super absorbent double ply virgin paper towels for spills and frying.',
        purchasePrice: 95,
        sellingPrice: 125,
        discount: 10,
        gst: 12,
        stockQuantity: 22,
        minimumStockLevel: 5,
        unit: 'packet',
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Odonil Room Air Freshener Jasmine Block (50 g)',
        sku: 'HOUS-ODO-047',
        barcode: '8901207030014',
        category: catMap['Household & Cleaning'],
        brand: 'Odonil',
        description: 'Continuous sweet jasmine fragrance block for bathroom and closets.',
        purchasePrice: 42,
        sellingPrice: 55,
        discount: 5,
        gst: 18,
        stockQuantity: 35,
        minimumStockLevel: 8,
        unit: 'piece',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Colin Glass and Surface Cleaner Spray (500 ml)',
        sku: 'HOUS-COL-048',
        barcode: '8901396050012',
        category: catMap['Household & Cleaning'],
        brand: 'Colin',
        description: 'Shine boosters for streak-free clean glass tables, windows, and mirrors.',
        purchasePrice: 85,
        sellingPrice: 105,
        discount: 5,
        gst: 18,
        stockQuantity: 28,
        minimumStockLevel: 6,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Dabur Honey 100% Pure Squeezy (400 g)',
        sku: 'SPIC-HNY-049',
        barcode: '8901207040013',
        category: catMap['Spices & Masalas'],
        brand: 'Dabur',
        description: 'NMR tested 100% pure natural honey in convenient squeezy pack.',
        purchasePrice: 180,
        sellingPrice: 220,
        discount: 15,
        gst: 5,
        stockQuantity: 25,
        minimumStockLevel: 5,
        unit: 'bottle',
        image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=500&q=80',
      },
      {
        name: 'Haldiram Soan Papdi Festive Gift Box (500 g)',
        sku: 'SNCK-SNP-050',
        barcode: '8904004402015',
        category: catMap['Snacks & Biscuits'],
        brand: 'Haldirams',
        description: 'Flaky melt-in-mouth traditional cardamom and pistachio sweet.',
        purchasePrice: 120,
        sellingPrice: 160,
        discount: 10,
        gst: 5,
        stockQuantity: 30,
        minimumStockLevel: 6,
        unit: 'box',
        image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=500&q=80',
      },
    ];

    const products = await Product.insertMany(productsData);

    const inventoryInTransactions = products.map((p) => ({
      product: p._id,
      type: 'IN',
      quantity: p.stockQuantity,
      previousStock: 0,
      newStock: p.stockQuantity,
      reason: 'Initial warehouse stock onboarding',
      createdBy: adminUser._id,
    }));
    await InventoryTransaction.insertMany(inventoryInTransactions);

    // 20 Customers
    const customersData = [
      { name: 'Sunil Aggarwal', phone: '+91 98110 12345', email: 'sunil.agg@gmail.com', address: 'B-42, Gulmohar Park', city: 'New Delhi', pincode: '110049' },
      { name: 'Priya Mehra', phone: '+91 98110 23456', email: 'priya.mehra@gmail.com', address: 'Flat 302, Palm Heights, Sector 14', city: 'Gurugram', pincode: '122001' },
      { name: 'Dr. Anand Saxena', phone: '+91 98110 34567', email: 'dr.anand@apollo.org', address: 'H-14, Green Park Extension', city: 'New Delhi', pincode: '110016' },
      { name: 'Kavita Chawla', phone: '+91 98110 45678', email: 'kavita.c@yahoo.com', address: 'C-7, Hauz Khas', city: 'New Delhi', pincode: '110016' },
      { name: 'Manish Malhotra', phone: '+91 98110 56789', email: 'manish.m@gmail.com', address: 'E-12, South Extension Part 2', city: 'New Delhi', pincode: '110049' },
      { name: 'Anita Roy', phone: '+91 98110 67890', email: 'anita.roy@gmail.com', address: 'A-108, Chittaranjan Park', city: 'New Delhi', pincode: '110019' },
      { name: 'Rajeev Bansal', phone: '+91 98110 78901', email: 'rajeev.bansal@outlook.com', address: 'House 55, Defence Colony', city: 'New Delhi', pincode: '110024' },
      { name: 'Sanjay Kapoor', phone: '+91 98110 89012', email: 'sanjay.k@rediffmail.com', address: 'Shop 3, Market Lane, Malviya Nagar', city: 'New Delhi', pincode: '110017' },
      { name: 'Neha Singhal', phone: '+91 98110 90123', email: 'neha.singhal@gmail.com', address: 'D-21, Saket', city: 'New Delhi', pincode: '110017' },
      { name: 'Harpreet Singh', phone: '+91 98110 01234', email: 'harpreet.singh@gmail.com', address: 'J-8, Lajpat Nagar 3', city: 'New Delhi', pincode: '110024' },
      { name: 'Geeta Nair', phone: '+91 98220 11223', email: 'geeta.nair@gmail.com', address: 'Flat 104, Jasmine Court, Indiranagar', city: 'Bengaluru', pincode: '560038' },
      { name: 'Karan Kundra', phone: '+91 98220 22334', email: 'karan.k@gmail.com', address: 'B-12, Vasant Vihar', city: 'New Delhi', pincode: '110057' },
      { name: 'Deepa Menon', phone: '+91 98220 33445', email: 'deepa.m@gmail.com', address: '74, Koramangala 4th Block', city: 'Bengaluru', pincode: '560034' },
      { name: 'Rohit Khanna', phone: '+91 98220 44556', email: 'rohit.khanna@gmail.com', address: 'Villa 18, Beverly Hills, Bandra West', city: 'Mumbai', pincode: '400050' },
      { name: 'Meenakshi Iyer', phone: '+91 98220 55667', email: 'meenakshi.i@gmail.com', address: 'F-3, Alaknanda Apartments', city: 'New Delhi', pincode: '110019' },
      { name: 'Arjun Rampal', phone: '+91 98220 66778', email: 'arjun.r@gmail.com', address: 'A-4, Greater Kailash 1', city: 'New Delhi', pincode: '110048' },
      { name: 'Shweta Tiwari', phone: '+91 98220 77889', email: 'shweta.t@gmail.com', address: 'Tower 4, Flat 1201, Noida Sector 62', city: 'Noida', pincode: '201301' },
      { name: 'Gaurav Sethi', phone: '+91 98220 88990', email: 'gaurav.sethi@gmail.com', address: 'C-99, Anand Niketan', city: 'New Delhi', pincode: '110021' },
      { name: 'Pooja Bhattacharya', phone: '+91 98220 99001', email: 'pooja.b@gmail.com', address: 'Flat 5B, Salt Lake Sector 1', city: 'Kolkata', pincode: '700064' },
      { name: 'Vikramaditya Roy', phone: '+91 98330 11122', email: 'vikram.roy@gmail.com', address: 'Plot 28, Safdarjung Enclave', city: 'New Delhi', pincode: '110029' },
    ];

    const customers = await Customer.insertMany(customersData);

    // 15 Sample Orders across sources
    const orderSources = ['WHATSAPP', 'PHONE', 'WALK_IN', 'WEBSITE', 'APP'];
    const paymentMethods = ['UPI', 'CASH', 'CARD', 'COD'];
    const dateToday = new Date();

    for (let i = 0; i < 15; i++) {
      const customer = customers[i % customers.length];
      const source = orderSources[i % orderSources.length];
      const pMethod = paymentMethods[i % paymentMethods.length];

      const prod1 = products[(i * 3) % products.length];
      const prod2 = products[(i * 3 + 1) % products.length];
      const prod3 = products[(i * 3 + 2) % products.length];

      const item1Qty = 2;
      const item2Qty = 1;
      const item3Qty = (i % 2 === 0) ? 3 : 1;

      const subtotal = (prod1.sellingPrice * item1Qty) + (prod2.sellingPrice * item2Qty) + (prod3.sellingPrice * item3Qty);
      const discount = (i % 3 === 0) ? 50 : 0;
      const gst = Math.round((subtotal * 0.05) * 100) / 100;
      const deliveryCharge = source === 'WALK_IN' ? 0 : 30;
      const totalAmount = Math.max(0, subtotal - discount + gst + deliveryCharge);

      const pastDate = new Date(dateToday);
      pastDate.setDate(pastDate.getDate() - (14 - i));

      const statusChoices = ['DELIVERED', 'DELIVERED', 'DELIVERED', 'OUT_FOR_DELIVERY', 'CONFIRMED', 'PROCESSING'];
      const status = i < 10 ? 'DELIVERED' : statusChoices[i % statusChoices.length];
      const orderNumber = `LK-${pastDate.toISOString().slice(0, 10).replace(/-/g, '')}-${String(1001 + i)}`;

      const order = await Order.create({
        orderNumber,
        customer: customer._id,
        items: [
          {
            product: prod1._id,
            name: prod1.name,
            sku: prod1.sku,
            price: prod1.sellingPrice,
            purchasePrice: prod1.purchasePrice,
            quantity: item1Qty,
            discount: 0,
            gst: Math.round((prod1.sellingPrice * item1Qty * (prod1.gst || 5) / 100) * 100) / 100,
            total: prod1.sellingPrice * item1Qty,
          },
          {
            product: prod2._id,
            name: prod2.name,
            sku: prod2.sku,
            price: prod2.sellingPrice,
            purchasePrice: prod2.purchasePrice,
            quantity: item2Qty,
            discount: 0,
            gst: Math.round((prod2.sellingPrice * item2Qty * (prod2.gst || 5) / 100) * 100) / 100,
            total: prod2.sellingPrice * item2Qty,
          },
          {
            product: prod3._id,
            name: prod3.name,
            sku: prod3.sku,
            price: prod3.sellingPrice,
            purchasePrice: prod3.purchasePrice,
            quantity: item3Qty,
            discount: 0,
            gst: Math.round((prod3.sellingPrice * item3Qty * (prod3.gst || 5) / 100) * 100) / 100,
            total: prod3.sellingPrice * item3Qty,
          },
        ],
        subtotal,
        discount,
        gst,
        deliveryCharge,
        totalAmount,
        paymentMethod: pMethod,
        paymentStatus: status === 'DELIVERED' ? 'PAID' : (pMethod === 'COD' ? 'PENDING' : 'PAID'),
        orderStatus: status,
        orderSource: source,
        deliveryAddress: {
          address: customer.address,
          city: customer.city,
          pincode: customer.pincode,
          phone: customer.phone,
        },
        notes: source === 'WHATSAPP' ? 'Converted from customer WhatsApp message' : '',
        createdBy: staffUsers[i % staffUsers.length]._id,
        createdAt: pastDate,
        updatedAt: pastDate,
      });

      await Customer.findByIdAndUpdate(customer._id, {
        $inc: { totalOrders: 1, totalSpending: totalAmount },
        lastOrderDate: pastDate,
      });

      if (source !== 'WALK_IN') {
        const partner = deliveryPartners[i % deliveryPartners.length];
        const delStatus = status === 'DELIVERED' ? 'DELIVERED' : (status === 'OUT_FOR_DELIVERY' ? 'OUT_FOR_DELIVERY' : 'ASSIGNED');
        await Delivery.create({
          order: order._id,
          customer: customer._id,
          phone: customer.phone,
          address: `${customer.address}, ${customer.city} ${customer.pincode}`,
          deliveryPartner: partner._id,
          status: delStatus,
          assignedDate: pastDate,
          deliveredDate: delStatus === 'DELIVERED' ? pastDate : undefined,
          notes: `Delivery via ${partner.name}`,
          createdAt: pastDate,
        });
      }

      await Payment.create({
        order: order._id,
        amount: totalAmount,
        method: pMethod,
        status: status === 'DELIVERED' ? 'PAID' : (pMethod === 'COD' ? 'PENDING' : 'PAID'),
        transactionId: pMethod === 'UPI' ? `UPI-TXN-${990000 + i}` : (pMethod === 'CARD' ? `POS-AUTH-${44000 + i}` : ''),
        notes: `Payment for order ${order.orderNumber}`,
        createdAt: pastDate,
      });
    }

    // Sample Notifications
    await Notification.create([
      {
        title: 'New WhatsApp Order',
        message: 'Order #LK-20260920-1014 received via WhatsApp for ₹1,120',
        type: 'NEW_ORDER',
        link: '/orders',
        isRead: false,
      },
      {
        title: 'Low Stock Alert',
        message: 'Product "Lifebuoy Handwash Refill" has reached low stock (3 remaining)',
        type: 'LOW_STOCK',
        link: '/inventory',
        isRead: false,
      },
      {
        title: 'Out of Stock Alert',
        message: 'Product "Wagh Bakri Premium CTC Tea" is OUT OF STOCK',
        type: 'OUT_OF_STOCK',
        link: '/inventory',
        isRead: false,
      },
      {
        title: 'Delivery Completed',
        message: 'Order #LK-20260918-1008 delivered successfully by Suresh Kumar',
        type: 'DELIVERY_COMPLETED',
        link: '/orders',
        isRead: true,
      },
    ]);

    console.log('[Seed] Database primed with initial data successfully.');
  } catch (error) {
    console.error('[Seed Error]:', error);
  }
};

module.exports = { seedAll };

// If run directly
if (require.main === module) {
  const { connectDB, disconnectDB } = require('../config/db');
  (async () => {
    await connectDB();
    await seedAll();
    await disconnectDB();
    process.exit(0);
  })();
}
